# SmashHit configuration

# Should criticals be enabled?
enable-criticals: true
# In 1.9, you can't achieve critical hits while sprinting.
# Enable this to use pre-1.9 behavior
old-criticals: false

# How many clicks per second are we allowing?
max-cps: 12

# How many blocks of reach can players have?
max-reach: 3.85

# Bridge to other PvP proteciton plugins
# WorldGuard bridge is currently not stable.
use-bridge:
  worldguard: false